export const mock_jobs = [
  {
    id: "1",
    title: "Long Haul Truck Driver",
    description:
      "We are seeking experienced long haul truck drivers to join our team. You will be responsible for transporting goods across long distances, ensuring timely delivery and maintaining a safe driving record.",

    carrier: {
      name: "Swift Transportation",
      avatar: "https://example.com/avatar1.png",
    },
    location: "Phoenix, AZ",
    salary: 65000,
    job_type: ["Full-time"],
    status: "active",
    posted_at: "2 days ago",
    num_openings: 1,
    country: "USA",
    language: "English",
    shift: "Day",
    day_range: "Monday to Friday",
    experience_level: "Entry",
    benefits: ["Health Insurance", "401k"],
    job_description: "Detailed job description here.",
    customized_pre_screening: [],
    qualifications: ["Valid CDL", "Clean driving record"],
    application_method: "Direct",
    freight_type: ["Dry Van"],
    vehicle_type: ["Truck"],
    home_time: ["Weekly"],
  },
  {
    id: "2",
    title: "Local Delivery Driver",
    description:
      "Join our team as a local delivery driver. You'll be responsible for delivering packages within the city limits, providing excellent customer service, and maintaining your vehicle.",

    carrier: {
      name: "FedEx",
      avatar: "https://example.com/avatar2.png",
    },
    location: "New York, NY",
    salary: 45000,
    job_type: ["Part-Time"],
    status: "active",

    posted_at: "1 week ago",
    num_openings: 1,
    country: "USA",
    language: "English",
    shift: "Day",
    day_range: "Monday to Friday",
    experience_level: "Entry",
    benefits: ["Health Insurance", "401k"],
    job_description: "Detailed job description here.",
    customized_pre_screening: [],
    qualifications: ["Valid CDL", "Clean driving record"],
    application_method: "Direct",
    freight_type: ["Reefer"],
    vehicle_type: ["Truck"],
    home_time: ["Weekly"],
  },
  {
    id: "3",
    title: "Refrigerated Truck Driver",
    description:
      "We're looking for experienced drivers to handle our refrigerated trucks. You'll be transporting temperature-sensitive goods across state lines, ensuring proper temperature control and timely delivery.",

    carrier: {
      name: "CR England",
      avatar: "https://example.com/avatar3.png",
    },
    location: "Salt Lake City, UT",
    salary: 70000,
    job_type: ["Full-Time"],
    status: "active",

    posted_at: "3 days ago",
    num_openings: 1,
    country: "USA",
    language: "English",
    shift: "Day",
    day_range: "Monday to Friday",
    experience_level: "Entry",
    benefits: ["Health Insurance", "401k"],
    job_description: "Detailed job description here.",
    customized_pre_screening: [],
    qualifications: ["Valid CDL", "Clean driving record"],
    application_method: "Direct",
    freight_type: ["Reefer"],
    vehicle_type: ["Truck"],
    home_time: ["Weekly"],
  },
  {
    id: "4",
    title: "Tanker Truck Driver",
    description:
      "Experienced tanker truck drivers needed for transporting liquid and gas products. Must have a clean driving record and relevant certifications.",

    carrier: {
      name: "Schneider National",
      avatar: "https://example.com/avatar4.png",
    },
    location: "Green Bay, WI",
    salary: 75000,
    job_type: ["Full-Time"],
    status: "active",
    posted_at: "5 days ago",
    num_openings: 1,
    country: "USA",
    language: "English",
    shift: "Day",
    day_range: "Monday to Friday",
    experience_level: "Entry",
    benefits: ["Health Insurance", "401k"],
    job_description: "Detailed job description here.",
    customized_pre_screening: [],
    qualifications: ["Valid CDL", "Clean driving record"],
    application_method: "Direct",
    freight_type: ["Hazmat"],
    vehicle_type: ["Truck"],
    home_time: ["Weekly"],
  },
  {
    id: "5",
    title: "Flatbed Truck Driver",
    description:
      "Join our flatbed division! We're seeking skilled drivers comfortable with securing and transporting oversized loads across the country.",

    carrier: {
      name: "Maverick Transportation",
      avatar: "https://example.com/avatar5.png",
    },
    location: "Little Rock, AR",
    salary: 68000,
    job_type: ["Full-Time"],
    status: "active",
    posted_at: "1 day ago",
    num_openings: 1,
    country: "USA",
    language: "English",
    shift: "Day",
    day_range: "Monday to Friday",
    experience_level: "Entry",
    benefits: ["Health Insurance", "401k"],
    job_description: "Detailed job description here.",
    customized_pre_screening: [],
    qualifications: ["Valid CDL", "Clean driving record"],
    application_method: "Direct",
    freight_type: ["Flatbed"],
    vehicle_type: ["Truck"],
    home_time: ["Weekly"],
  },
  {
    id: "6",
    title: "Regional Truck Driver",
    description:
      "Regional truck driver needed for routes within the Midwest. Home weekly with competitive pay and benefits.",

    carrier: {
      name: "Werner Enterprises",
      avatar: "https://example.com/avatar6.png",
    },
    location: "Omaha, NE",
    salary: 60000,
    job_type: ["Full-Time"],
    status: "active",
    posted_at: "4 days ago",
    num_openings: 1,
    country: "USA",
    language: "English",
    shift: "Day",
    day_range: "Monday to Friday",
    experience_level: "Entry",
    benefits: ["Health Insurance", "401k"],
    job_description: "Detailed job description here.",
    customized_pre_screening: [],
    qualifications: ["Valid CDL", "Clean driving record"],
    application_method: "Direct",
    freight_type: ["Dry Van"],
    vehicle_type: ["Truck"],
    home_time: ["Weekly"],
  },
  {
    id: "7",
    title: "Team Truck Driver",
    description:
      "Looking for a driving partner? Join our team driving program! Share the road and increase your earning potential.",

    carrier: {
      name: "Prime Inc.",
      avatar: "https://example.com/avatar7.png",
    },
    location: "Springfield, MO",
    salary: 80000,
    job_type: ["Full-Time"],
    status: "active",
    posted_at: "2 weeks ago",
    num_openings: 1,
    country: "USA",
    language: "English",
    shift: "Day",
    day_range: "Monday to Friday",
    experience_level: "Entry",
    benefits: ["Health Insurance", "401k"],
    job_description: "Detailed job description here.",
    customized_pre_screening: [],
    qualifications: ["Valid CDL", "Clean driving record"],
    application_method: "Direct",
    freight_type: ["Dry Van"],
    vehicle_type: ["Truck"],
    home_time: ["Weekly"],
  },
  {
    id: "8",
    title: "Hazmat Truck Driver",
    description:
      "Hazmat certified drivers needed for transporting dangerous goods. Must have all relevant certifications and a spotless driving record.",

    carrier: {
      name: "JB Hunt",
      avatar: "https://example.com/avatar8.png",
    },
    location: "Lowell, AR",
    salary: 85000,
    job_type: ["Full-Time"],
    status: "active",
    posted_at: "6 days ago",
    num_openings: 1,
    country: "USA",
    language: "English",
    shift: "Day",
    day_range: "Monday to Friday",
    experience_level: "Entry",
    benefits: ["Health Insurance", "401k"],
    job_description: "Detailed job description here.",
    customized_pre_screening: [],
    qualifications: ["Valid CDL", "Clean driving record"],
    application_method: "Direct",
    freight_type: ["Hazmat"],
    vehicle_type: ["Truck"],
    home_time: ["Weekly"],
  },
  {
    id: "9",
    title: "Dump Truck Driver",
    description:
      "Local dump truck driver needed for construction sites. Must be comfortable operating heavy machinery and have a valid CDL.",

    carrier: {
      name: "waste_management",
      avatar: "https://example.com/avatar9.png",
    },
    location: "Houston TX",
    salary: 55000,
    job_type: ["Full-Time"],
    status: "active",
    posted_at: "3 days ago",
    num_openings: 1,
    country: "USA",
    language: "English",
    shift: "Day",
    day_range: "Monday to Friday",
    experience_level: "Entry",
    benefits: ["Health Insurance", "401k"],
    job_description: "Detailed job description here.",
    customized_pre_screening: [],
    qualifications: ["Valid CDL", "Clean driving record"],
    application_method: "Direct",
    freight_type: ["Flatbed"],
    vehicle_type: ["Truck"],
    home_time: ["Weekly"],
  },
  {
    id: "10",
    title: "Auto-Hauler",
    description:
      "Experienced auto haulers needed for transporting vehicles across the country. Must be comfortable with specialized equipment and securing various types of vehicles.",
    carrier: {
      name: "United-Road",
      avatar: "https://example.com/avatar10.png",
    },
    location: "Romulus-MI",
    salary: 72000,
    job_type: ["Full-Time"],
    status: "active",
    posted_at: "1 week ago",
    num_openings: 1,
    country: "USA",
    language: "English",
    shift: "Day",
    day_range: "Monday to Friday",
    experience_level: "Entry",
    benefits: ["Health Insurance", "401k"],
    job_description: "Detailed job description here.",
    customized_pre_screening: [],
    qualifications: ["Valid CDL", "Clean driving record"],
    application_method: "Direct",
    freight_type: ["Dry Van"],
    vehicle_type: ["Truck"],
    home_time: ["Weekly"],
  },
];
